name: katcorr
channels:
- conda-forge
- tpeulen
- schrodinger
- salilab
- defaults
dependencies:
- tttrlib
- git=2.24.0
- hdf5=1.10.5
- ipython=7.10.2
- matplotlib=3.1.2
- matplotlib-base=3.1.2
- numba=0.46.0
- numpy=1.17.3
- pyqt=5.12.3
- python=3.7.3
- qt=5.12.5
- scipy=1.3.2